### ISSUE TITLE
[ENTREGA PARCIAL RECU OBJETOS] BAUTISTA JAUREGUI

### ISSUE THREAD

**Issue by bautijau** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-bautijau#1]
Asegurense de actualizar el nombre del issue con su grupo y el número de TP que están entregando (reemplazá el # por el número correspondiente).

Dejen acá el aviso a tus tutores, arrobando sus ids para que les llegue una notificación, y aclaren lo que crean necesario.

Pueden encontrar en la [planilla del curso](https://www.pdep.com.ar/cursos/lunes-tarde#h.he7ifb72x6mp) quienes son tus tutores. 

**Borren los ids de los tutores que no son de tu grupo así no les llega una notificación a todos:**
Emiliano Salvano y Luca Pavón @EmilianoSalvano @Lpavn
Juan Fernandes y Lucas Zheng @juanFdS @zhl27 
Juani Schuhmann y Dante Ortiz @jschuhmann47 @Effloresc3 
Tomás Antonio @T-J-Antonio
Gustavo Crespi y Manuel Torrente @gcrespi @manutorrente

**Comment by JuanFdS** [comment]
## Parte A
### Punto 1
⚠️ ¿Por qué el mago tiene un método `configurar` con esos parámetros, en lugar de pasarlos al instanciar la clase?
⚠️ Los valores por defecto de las variables internas no guardan relación con el enunciado.
⚠️ Si querías que el método `poderAportado` de la superclase `ObjetoMagico` fuera abstracto, debías sacar las llaves después de la firma.
❌ Las túnicas también tienen poder base según el enunciado. Además, las túnicas toman la resistencia propia del mago para calcular su poder aportado.
❌ Dado que el mensaje `/` no realiza una división entera, la verificación de si el nombre del mago tiene longitud par en las varitas es incorrecta.
### Punto 2
❌ No se implementan las categorías (aprendiz, veterano, inmortal).
❌ ¿Por qué el mago, al desafiar a otro, recibe por parámetro unos puntos de energía? Ambos magos tienen sus reservas y sólo ellas deberían ser tenidas en cuenta.
⚠️ El método no tiene por qué tener un valor de retorno, al ser un método de efecto lo que interesa es _lo que hace_, no _lo que retorna_.
En virtud de que no están las categorías, está incompleto ❌
## Parte B
### Punto 1
❌ La validación está en el método `configurar` de la clase `Gremios`, por lo tanto para hacer la validación, el gremio ya debe haber sido creado previamente, y pudo haber sido creado de manera inválida. La validación, como indica la consigna, debería estar ubicada en el método `initialize` de la clase o bien en un objeto con la responsabilidad de crear gremios.
### Punto 2
❌ La lógica de los puntos de energía es incorrecta al igual que en la parte A.
❌ Dado que los gremios no entienden el mensaje `restarEnergia`, los gremios no pueden ser desafiados por otros en esta implementación, cuando según el enunciado deberían poder.
### Punto 3
❌ Incompleto.
## Tests
N/A.

----------------------

Nota: 2
